version: "3"

services:
  web:
    build: .
    image: oc-lettings-site
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: keinos/sqlite3
    environment:
      - SQLITE3_DATABASE=/data/oc-lettings-site.sqlite3
    volumes:
      - ./oc-lettings-site.sqlite3:/data/oc-lettings-site.sqlite3
    restart: always