version: 2.1

jobs:
  build-test-and-lint:
    docker:
      - image: "circleci/python:3.10.0"
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            flake8
  dockerize:
    docker:
      - image: docker:latest
    environment:
      DOCKER_DRIVER: overlay2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t bricevne/oc-lettings-site:$CIRCLE_SHA1 .
            docker login -u bricevne -p $DOCKERHUB_PASSWORD
            docker push bricevne/oc-lettings-site:$CIRCLE_SHA1
            docker tag bricevne/oc-lettings-site:$CIRCLE_SHA1 bricevne/oc-lettings-site:latest
            docker push bricevne/oc-lettings-site:latest

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-lint
      - dockerize:
          requires:
            - build-test-and-lint
          filters:
            branches:
              only: master
#      - deploy:
#          requires:
#            dockerize
#          filters:
#            branches:
#              only: master
