version: 2.1

jobs:
  build-test-and-lint:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-v1-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install --upgrade pip
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-v1-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            flake8
  dockerize:
    docker:
      - image: docker:latest
    environment:
      DOCKER_DRIVER: overlay2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build, tag and push Docker image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build -t $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1 .
            docker push $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1
            docker tag $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1 $DOCKERHUB_USERNAME/oc-lettings-site:latest
            docker push $DOCKERHUB_USERNAME/oc-lettings-site:latest
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Pulling container from Dockerhub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker pull $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1

      - run:
          name: Pushing container to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku create $HEROKU_APP_NAME --region eu || true
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DEBUG=$DEBUG -a $HEROKU_APP_NAME
            docker tag $DOCKERHUB_USERNAME/oc-lettings-site:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - run:
          name: Releasing container
          command: |          
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web -a $HEROKU_APP_NAME

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-lint
      - dockerize:
          requires:
            - build-test-and-lint
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - dockerize
          filters:
            branches:
              only: master
