version: 2.1

jobs:
  build-test-and-lint:
    docker:
      - image: "circleci/python:3.10.0"
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Install Git
          command: |
            . venv/bin/activate
            sudo apt-get update
            sudo apt-get install -y git
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            flake8
  dockerize:
    docker:
      - image: docker:latest
    environment:
      DOCKER_DRIVER: overlay2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and tag Docker image
          command: |
            IMAGE_NAME=bricevne/oc-lettings-site
            IMAGE_TAG=$(PATH=$PATH:/usr/bin/git git rev-parse --short HEAD)
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker login -u bricevne -p $DOCKERHUB_PASSWORD
            docker push $IMAGE_NAME:$IMAGE_TAG
            docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-lint
      - dockerize:
          requires:
            - build-test-and-lint
          filters:
            branches:
              only: master
#      - deploy:
#          requires:
#            dockerize
#          filters:
#            branches:
#              only: master
